import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/reference/api/sidebar";

// Add unique keys to API sidebar categories to avoid translation key conflicts
// with SDK reference categories that share the same tag names.
const apiSidebarWithKeys = apiSidebar.map((item) => {
  if (item.type === "category") {
    return { ...item, key: `api-${item.label}` };
  }
  return item;
});

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started/index" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Mods",
      link: { type: "doc", id: "mods/index" },
      items: [{ type: "autogenerated", dirName: "mods" }],
    },
    {
      type: "category",
      label: "MOD Development",
      link: { type: "doc", id: "mod-development/index" },
      items: [{ type: "autogenerated", dirName: "mod-development" }],
    },
    {
      type: "category",
      label: "AI Integration",
      link: { type: "doc", id: "ai-integration/index" },
      items: [{ type: "autogenerated", dirName: "ai-integration" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/index" },
      items: [
        {
          type: "category",
          label: "API",
          items: apiSidebarWithKeys,
        },
        {
          type: "category",
          label: "SDK",
          link: { type: "doc", id: "reference/sdk/index" },
          items: [{ type: "autogenerated", dirName: "reference/sdk" }],
        },
        { type: "autogenerated", dirName: "reference/cli" },
        { type: "autogenerated", dirName: "reference/mcp-tools" },
      ],
    },
    {
      type: "category",
      label: "Contributing",
      link: { type: "doc", id: "contributing/index" },
      items: [{ type: "autogenerated", dirName: "contributing" }],
    },
  ],
};

export default sidebars;
