import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started/index" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Mods",
      link: { type: "doc", id: "mods/index" },
      items: [{ type: "autogenerated", dirName: "mods" }],
    },
    {
      type: "category",
      label: "MOD Development",
      link: { type: "doc", id: "mod-development/index" },
      items: [{ type: "autogenerated", dirName: "mod-development" }],
    },
    {
      type: "category",
      label: "AI Integration",
      link: { type: "doc", id: "ai-integration/index" },
      items: [{ type: "autogenerated", dirName: "ai-integration" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/index" },
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
    {
      type: "doc",
      id: "contributing/index",
      label: "Contributing",
    },
  ],
};

export default sidebars;
