import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/api/homunculus-api",
    },
    {
      type: "category",
      label: "app",
      items: [
        {
          type: "doc",
          id: "reference/api/exit",
          label: "POST /app/exit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/health",
          label: "GET /app/health",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-app-info",
          label: "GET /app/info",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "audio",
      items: [
        {
          type: "doc",
          id: "reference/api/bgm-status",
          label: "GET /audio/bgm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/bgm-play",
          label: "POST /audio/bgm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/bgm-update",
          label: "PATCH /audio/bgm",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/bgm-pause",
          label: "POST /audio/bgm/pause",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/bgm-resume",
          label: "POST /audio/bgm/resume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/bgm-stop",
          label: "POST /audio/bgm/stop",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/se-play",
          label: "POST /audio/se",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "personas",
      items: [
        {
          type: "doc",
          id: "reference/api/list-personas",
          label: "GET /personas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/create",
          label: "POST /personas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/snapshot",
          label: "GET /personas/snapshot",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/stream",
          label: "GET /personas/stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-persona",
          label: "GET /personas/{id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-persona",
          label: "DELETE /personas/{id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/update-persona",
          label: "PATCH /personas/{id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/get-age",
          label: "GET /personas/{id}/age",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-age",
          label: "PUT /personas/{id}/age",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/despawn",
          label: "POST /personas/{id}/despawn",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/events",
          label: "GET /personas/{id}/events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-first-person-pronoun",
          label: "GET /personas/{id}/first-person-pronoun",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-first-person-pronoun",
          label: "PUT /personas/{id}/first-person-pronoun",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-gender",
          label: "GET /personas/{id}/gender",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-gender",
          label: "PUT /personas/{id}/gender",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-metadata",
          label: "GET /personas/{id}/metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-metadata",
          label: "PUT /personas/{id}/metadata",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-name",
          label: "GET /personas/{id}/name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-name",
          label: "PUT /personas/{id}/name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-personality",
          label: "GET /personas/{id}/personality",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-personality",
          label: "PUT /personas/{id}/personality",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-profile",
          label: "GET /personas/{id}/profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-profile",
          label: "PUT /personas/{id}/profile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/spawn",
          label: "POST /personas/{id}/spawn",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-persona-state",
          label: "GET /personas/{id}/state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-persona-state",
          label: "PUT /personas/{id}/state",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-thumbnail",
          label: "GET /personas/{id}/thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/put-thumbnail",
          label: "PUT /personas/{id}/thumbnail",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-persona-transform",
          label: "GET /personas/{id}/transform",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-persona-transform",
          label: "PUT /personas/{id}/transform",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/attach",
          label: "POST /personas/{id}/vrm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/detach",
          label: "DELETE /personas/{id}/vrm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/get-bone",
          label: "GET /personas/{id}/vrm/bone/{bone_name}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-expressions",
          label: "GET /personas/{id}/vrm/expressions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/clear-expressions",
          label: "DELETE /personas/{id}/vrm/expressions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/modify-expressions",
          label: "PATCH /personas/{id}/vrm/expressions",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/unlook",
          label: "DELETE /personas/{id}/vrm/look",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/look-cursor",
          label: "PUT /personas/{id}/vrm/look/cursor",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/look-target",
          label: "PUT /personas/{id}/vrm/look/target/{target}",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/get-position",
          label: "GET /personas/{id}/vrm/position",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/speech-timeline",
          label: "POST /personas/{id}/vrm/speech/timeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-spring-bones",
          label: "GET /personas/{id}/vrm/spring-bones",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/patch-spring-bones",
          label: "PATCH /personas/{id}/vrm/spring-bones/{chain_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/get-vrma",
          label: "GET /personas/{id}/vrm/vrma",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/play-vrma",
          label: "POST /personas/{id}/vrm/vrma/play",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/stop-vrma",
          label: "POST /personas/{id}/vrm/vrma/stop",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "entities",
      items: [
        {
          type: "doc",
          id: "reference/api/find-entity",
          label: "GET /entities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/move-to",
          label: "POST /entities/{entity}/move",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-entity-name",
          label: "GET /entities/{entity}/name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-transform",
          label: "GET /entities/{entity}/transform",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-transform",
          label: "PUT /entities/{entity}/transform",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/tween-position",
          label: "POST /entities/{entity}/tween/position",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/tween-rotation",
          label: "POST /entities/{entity}/tween/rotation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/tween-scale",
          label: "POST /entities/{entity}/tween/scale",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "webviews",
      items: [
        {
          type: "doc",
          id: "reference/api/list-webviews",
          label: "GET /webviews",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/open",
          label: "POST /webviews",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/get-webview",
          label: "GET /webviews/{entity}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/delete-webview",
          label: "DELETE /webviews/{entity}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/update-webview",
          label: "PATCH /webviews/{entity}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/api/is-closed",
          label: "GET /webviews/{entity}/is-closed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-linked-persona",
          label: "GET /webviews/{entity}/linked-persona",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-linked-persona",
          label: "PUT /webviews/{entity}/linked-persona",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/api/unlink-persona",
          label: "DELETE /webviews/{entity}/linked-persona",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/navigate",
          label: "POST /webviews/{entity}/navigate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/navigate-back",
          label: "POST /webviews/{entity}/navigate/back",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/navigate-forward",
          label: "POST /webviews/{entity}/navigate/forward",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/reload",
          label: "POST /webviews/{entity}/reload",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "coordinates",
      items: [
        {
          type: "doc",
          id: "reference/api/global-viewport",
          label: "GET /coordinates/to-viewport",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/world-2-d",
          label: "GET /coordinates/to-world",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "effects",
      items: [
        {
          type: "doc",
          id: "reference/api/stamp",
          label: "POST /effects/stamps",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "preferences",
      items: [
        {
          type: "doc",
          id: "reference/api/list-preferences",
          label: "GET /preferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/load",
          label: "GET /preferences/{key}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/save",
          label: "PUT /preferences/{key}",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "signals",
      items: [
        {
          type: "doc",
          id: "reference/api/list-signals",
          label: "GET /signals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/send",
          label: "POST /signals/{signal}",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "settings",
      items: [
        {
          type: "doc",
          id: "reference/api/get-fps",
          label: "GET /settings/fps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-fps",
          label: "PUT /settings/fps",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "shadow-panel",
      items: [
        {
          type: "doc",
          id: "reference/api/get-shadow-alpha",
          label: "GET /shadow-panel/alpha",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/set-shadow-alpha",
          label: "PUT /shadow-panel/alpha",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "displays",
      items: [
        {
          type: "doc",
          id: "reference/api/all",
          label: "GET /displays",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "mods",
      items: [
        {
          type: "doc",
          id: "reference/api/list-mods",
          label: "GET /mods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-menus",
          label: "GET /mods/menus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-one",
          label: "GET /mods/{mod_name}",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "commands",
      items: [
        {
          type: "doc",
          id: "reference/api/execute-command",
          label: "POST /commands/execute",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "processes",
      items: [
        {
          type: "doc",
          id: "reference/api/list-processes",
          label: "GET /processes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/start",
          label: "POST /processes/start",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/stop",
          label: "DELETE /processes/{handle_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "assets",
      items: [
        {
          type: "doc",
          id: "reference/api/list-assets",
          label: "GET /assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/get-asset-file",
          label: "GET /assets/file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/import",
          label: "POST /assets/import",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "rpc",
      items: [
        {
          type: "doc",
          id: "reference/api/call",
          label: "POST /rpc/call",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/deregister",
          label: "POST /rpc/deregister",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/register",
          label: "POST /rpc/register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/list-registrations",
          label: "GET /rpc/registrations",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "stt",
      items: [
        {
          type: "doc",
          id: "reference/api/list-languages",
          label: "GET /stt/languages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/list-models",
          label: "GET /stt/models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/api/download-model",
          label: "POST /stt/models/download",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/cancel-download",
          label: "DELETE /stt/models/download",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/api/download-model-stream",
          label: "POST /stt/models/download/stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/ptt-start",
          label: "POST /stt/ptt/start",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/ptt-stop",
          label: "POST /stt/ptt/{session_id}/stop",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/recognize",
          label: "POST /stt/recognize",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "dialog",
      items: [
        {
          type: "doc",
          id: "reference/api/pick-file",
          label: "POST /dialog/pick-file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/pick-files",
          label: "POST /dialog/pick-files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/api/pick-folder",
          label: "POST /dialog/pick-folder",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
